image: golang:1.12

variables:
    DOCKER_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}
    GOFLAGS: -mod=readonly
    GOPATH: ${CI_PROJECT_DIR}/vendor/go

stages:
    - dependencies
    - test
    - build
    - packaging

.modcache: &modcache
    key: modcache
    paths:
        - vendor/go/pkg/mod/


dependencies:
    stage: dependencies
    script: go mod download
    cache: *modcache

test:
    stage: test
    script: make test
    cache:
        <<: *modcache
        policy: pull
    artifacts:
        reports:
            junit: build/test_results/main/results.xml

test-integration:
    stage: test
    script: make test-integration
    cache:
        <<: *modcache
        policy: pull
    artifacts:
        reports:
            junit: build/test_results/integration/results.xml

lint:
    stage: test
    script: make lint
    cache:
        <<: *modcache
        policy: pull

.build: &build_definition
    stage: build
    script:
        - export CI_BUILD_DATE=$(date +%FT%T%z)
        - make build-release VERSION=${CI_COMMIT_REF_NAME} COMMIT_HASH=${CI_COMMIT_SHA} BUILD_DATE=${CI_BUILD_DATE}
        - make build-debug VERSION=${CI_COMMIT_REF_NAME} COMMIT_HASH=${CI_COMMIT_SHA} BUILD_DATE=${CI_BUILD_DATE}
    cache:
        <<: *modcache
        policy: pull

snapshot:
    <<: *build_definition
    only:
        - master
    artifacts:
        paths:
            - build/
        expire_in: 2 days

release:
    <<: *build_definition
    only:
        - tags
    artifacts:
        paths:
            - build/

.docker: &docker_definition
    stage: packaging
    image: docker:stable
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    services:
        - docker:dind
    before_script:
        - docker info
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
        - apk add --update --no-cache ca-certificates make
    script:
        - docker build --build-arg BUILD_DIR=build/release --build-arg BINARY_NAME=$(make var-BINARY_NAME) -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME} -f Dockerfile.local .
        - docker build --build-arg BUILD_DIR=build/debug --build-arg BINARY_NAME=$(make var-BINARY_NAME) -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}-debug -f Dockerfile.debug .
        - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}
        - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}-debug

docker:snapshot:
    <<: *docker_definition
    dependencies:
        - snapshot
    only:
        - master

docker:release:
    <<: *docker_definition
    dependencies:
        - release
    only:
        - tags
    script:
        - docker build --build-arg BUILD_DIR=build/release --build-arg BINARY_NAME=$(make var-BINARY_NAME) -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME} -f Dockerfile.local .
        - docker build --build-arg BUILD_DIR=build/release --build-arg BINARY_NAME=$(make var-BINARY_NAME) -t ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}-debug -f Dockerfile.debug .
        - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}
        - docker push ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}-debug
        - docker tag ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME} ${DOCKER_IMAGE}:latest
        - docker tag ${DOCKER_IMAGE}:${CI_COMMIT_REF_NAME}-debug ${DOCKER_IMAGE}:latest-debug
        - docker push ${DOCKER_IMAGE}:latest
        - docker push ${DOCKER_IMAGE}:latest-debug
