workspace:
  base: /cicd
pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.10
    cluster:
      name: tarokkkjges
      location: eu-west-1
      cloud: amazon
      secretId: f58b4090aaf3c6d4b703e2e42558d73fcbb0150506ed95498b7e5d6b25731b8d
      secretName: ""
      profileName: ""
      postHooks:
        InstallLogging:
          bucketName: logtest-new
          secretId: f58b4090aaf3c6d4b703e2e42558d73fcbb0150506ed95498b7e5d6b25731b8d
        InstallMonitoring:
          enabled: true
      properties:
        pke:
          nodepools:
          - name: master
            roles:
            - master
            hosts: []
            provider: amazon
            providerConfig:
              autoScalingGroup:
                instanceType: c5.large
                launchConfigurationName: master
                name: master
                size:
                  desired: 1
                  max: 1
                  min: 1
                spotPrice: ""
                zones:
                - eu-west-1a
            autoscaling: false
          - name: system
            roles:
            - pipeline-system
            hosts: []
            provider: amazon
            providerConfig:
              autoScalingGroup:
                instanceType: t2.medium
                launchConfigurationName: system
                name: system
                size:
                  desired: 1
                  max: 1
                  min: 1
                spotPrice: ""
                zones:
                - eu-west-1a
            autoscaling: false
          - name: pool2
            roles:
            - worker
            hosts: []
            provider: amazon
            providerConfig:
              autoScalingGroup:
                instanceType: c5.large
                launchConfigurationName: pool2
                name: pool2
                size:
                  desired: 1
                  max: 2
                  min: 1
                spotPrice: "0.1"
                zones:
                - eu-west-1a
            autoscaling: true
          kubernetes:
            version: 1.12.2
            rbac:
              enabled: true
          cri:
            runtime: containerd
            runtimeConfig: {}
          dexenabled: false
    action: EnsureCluster
  test:
    image: golang:1.12
    commands: make check
    environment:
      GOFLAGS: -mod=readonly
  build_image:
    dockerfile: Dockerfile
    image: plugins/docker
    repo: '{{ .CICD_REPO }}'
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: docker
      DOCKER_USERNAME:
        keyRef: username
        name: docker
    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
  package_application:
    when:
      branch:
        include:
        - master
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
    - helm package ./.banzaicloud/charts/spotguide-modern-go-application
  install_mysql_user_credentials_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mysql-user'
      namespace: default
      sourceSecretName: modern-go-test-mysql-user-credentials
      spec:
      - name: mysql-username
        source: username
      - name: mysql-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.10
    when:
      branch:
        include:
        - master
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-modern-go-application-0.2.0.tgz
      namespace: default
      releaseName: '{{ .CICD_REPO_NAME }}'
      reuseValues: true
      timeout: 900
      values:
        application:
          config:
            instrumentation:
              prometheus:
                enabled: true
          image:
            pullPolicy: Always
            repository: '{{ .CICD_REPO }}'
            tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
          ingress:
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/redirect-permanent: "true"
              traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
              traefik.ingress.kubernetes.io/redirect-replacement: https://$1
            enabled: true
            hosts:
            - app-{{ .CICD_REPO_NAME }}.{{ .CLUSTER_NAME }}.{{ .ORG_NAME }}.{{ .DOMAIN_NAME }}
        mysql:
          database: app
          enabled: true
          existingUserSecret: '{{ .CICD_REPO_NAME }}-mysql-user'
          metrics:
            enabled: true
          port: null
        nameOverride: '{{ .CICD_REPO_NAME }}'
      wait: true
    image: banzaicloud/ci-pipeline-client:0.10
    when:
      branch:
        include:
        - master
